export const seedPosts = [
  { id: 101, u: 4, g: "ダンス部", d: "2時間前", ds: "来月の発表会に向けて振り入れが終わりました。あと3回練習したら通しで踊れそうです。見学も歓迎なので気軽に覗きに来てください。",
    comments: [{ id: 1, u: 8, text: "見に行きたいです！", d: "1時間前" }, { id: 2, u: 2, text: "衣装どうします？", d: "40分前" }],
    interested: true, likes: 6, joined: [] },
  { id: 102, u: 7, g: "麻雀部", d: "5時間前", ds: "今週の卓会、あと1人で4人揃います。初心者の方でもルール説明しながらやるので大丈夫です。",
    comments: [{ id: 1, u: 3, text: "行けます！", d: "3時間前" }],
    recruiting: true, joined: ["田中次郎"], likes: 0 },
  { id: 103, u: 2, g: "バスケ部", d: "昨日", ds: "体育館の予約が取れたので今週末も練習できます。シューズ忘れずに。",
    comments: [], interested: true, likes: 4, joined: [] },
  { id: 104, u: 1, g: "フットサル部", d: "2日前", ds: "9月の大会、無事に終わりました。参加してくれたみなさんありがとうございました。次は12月です。",
    comments: [{ id: 1, u: 5, text: "お疲れさまでした！", d: "2日前" }, { id: 2, u: 6, text: "楽しかったです", d: "1日前" }, { id: 3, u: 3, text: "次も出ます", d: "1日前" }],
    interested: true, likes: 11, joined: [] },
  { id: 105, u: 3, g: "ダーツ部", d: "3日前", ds: "部内トーナメント、今回は高橋さんが優勝でした。次回は10月15日です。",
    comments: [{ id: 1, u: 5, text: "おめでとうございます", d: "3日前" }],
    interested: true, likes: 5, joined: [] },
];
